# Use a minimal base image.
language: c

# Do not spam us with build status emails please.
notifications:
  email: false

addons:
  apt:
    sources:
      - fpcomplete-trusty
    packages:
      # Haskell requires libgmp for big integers.
      - libgmp-dev

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/server/.stack-work
    - $TRAVIS_BUILD_DIR/client-haskell/.stack-work

before_install:
# Download and unpack the stack executable
# We need the latest version to work around some bugs in older versions of stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Install the compiler. Pass --no-terminal to tell Stack it is not running in
  # an interactive terminal, so it prints messages sequentially instead of
  # updating them. The latter is less spammy but Travis does not support these
  # interactive terminal capabilities.
  - (cd server && stack setup -j2 --no-terminal)
  - (cd client-haskell && stack setup -j2 --no-terminal)
  - curl -o install-nix-2.3.1 https://nixos.org/releases/nix/nix-2.3.1/install
  - sha256sum --check nix/nix_sha256sums
  - sh ./install-nix-2.3.1 --no-daemon
  - . $HOME/.nix-profile/etc/profile.d/nix.sh

jobs:
  include:
    - script:
      # Build and test.
      - (cd server && stack build -j2 --no-terminal)
      - (cd server && stack test  -j2 --no-terminal)
    - script:
      - (cd client-haskell && stack build -j2 --no-terminal)
      - (cd client-haskell && stack test  -j2 --no-terminal)
    # Check that the nix builds work
    - script:
      - nix-build --no-out-link -E '(import ./nix/nixpkgs.nix {}).haskellPackages.callPackage ./client-haskell/client.nix {}'
    - script:
      - nix-build --no-out-link ./server/default.nix
