resolver: lts-15.3

extra-deps:
  - raven-haskell-0.1.2.1
  - prometheus-metrics-ghc-1.0.0
  - wai-middleware-prometheus-1.0.0
  - sqlite-simple-0.4.18.0
  - direct-sqlite-2.3.26

# Reduce verbosity of stack output while compiling dependencies.
build:
  interleaved-output: false

# Note: This section will be ignored by stack, on non-NixOS systems.
# It can be explicitly enabled on non-NixOS systems by passing --nix.
# On NixOS this section is needed to bring the non-Haskell dependencies
# into scope.
nix:
  packages:
    - zlib
  path:
    - "nixpkgs=../nix/nixpkgs.nix"
